# Generated by Django 5.2.8 on 2025-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='hackathon', max_length=50),
        ),
    ]
